### ISSUE TITLE
siad becomes unreachable if socat dies 

### ISSUE THREAD

**Issue by jkawamoto** [NebulousLabs/docker-sia#3]
It'd be better to restart socat or exit the container.

We can check if port 9980 is working. However, since 9980 might not respond while loading, it's not easy to find whether socat dies or siad is still loading.

**Comment by ro-tex** [comment]
@jkawamoto thank you for the report! We're going to look into it.

**Comment by ro-tex** [comment]
@jkawamoto this is an interesting problem. I suggest that we address that by adding a healthcheck and marking the container as unhealthy if `socat` dies. This will allow us to monitor and restart the container in such cases.

In your experience, does it happen for `socat` to stop working properly without exiting? If so we can adjust the healthcheck logic.

**Comment by jkawamoto** [comment]
Thank you for adding the healthcheck.

I don't remember if socat has ever stopped working without exiting. I'll use the new healthcheck and see if it covers all cases in practice.
