### ISSUE TITLE
Error while building docker image

### ISSUE THREAD

**Issue by oroian-raul** [NebulousLabs/docker-sia#49]
Building a docker image from tag 1.5.1 fails with error:
```Step 16/25 : RUN ln -s "$SIA_DATA_DIR" /mnt/sia
 ---> Running in a1824cd9be34
ln: /mnt/sia: No such file or directory
The command '/bin/sh -c ln -s "$SIA_DATA_DIR" /mnt/sia' returned a non-zero code: 1

**Comment by ro-tex** [comment]
Have you, by any chance, somehow ended up with an empty `SIA_DATA_DIR` environment variable? That's the only way I can see this happening.

If that's not the case, please share your code.

**Update:**

I just tested it and it results in your error.

Build command (in `docker-sia`'s root directory):
```
docker build --build-arg SIA_DATA_DIR="" .
```

Output
```
ln: failed to create symbolic link '/mnt/sia' -> '': No such file or directory
The command '/bin/sh -c ln -s "$SIA_DATA_DIR" /mnt/sia' returned a non-zero code: 1
```

**Comment by ro-tex** [comment]
It's been 26 days since the last communication here, so I'll close this issue. If the problem resurfaces, feel free to reopen.
