### ISSUE TITLE
Possibility to have the consensus in another volume

### ISSUE THREAD

**Issue by polpas** [NebulousLabs/docker-sia#50]
In order to have skynet and consensus working in full speed wirh an SSD is there a way to have them in a spearate volume?

Is it possible to pass it as an argument when we execute the docker file?

**Comment by ro-tex** [comment]
Well, `siad` controls where it stores the consensus and the rest of its data (except the `apipassword`) via the `SIAD_DATA_DIR` environment variable. So it will not allow you to control that via docker arguments alone.

What you **could** try is:
* modify your image to have some other entrypoint, so you can stop `siad`
* start your container and mount the volume, as usual
* stop (or not start at all) `siad`, so you can mess with its data safely
* go in the volume directory (from your operating system, not from the container side)
* move the data you want to some other disk and replace its directory with a symlink to the new location

I haven't tried this and I'm not sure it would work but it seems like a potential way to achieve what you want.

**Before doing all this**, it's worth digging a little bit into the question. What, exactly, do you mean by "skynet and consensus working in full speed"? Are you trying to maximize Skynet's throughput and are worried that syncing the consensus will use up I/O and thus slow you down? While this is factually correct, syncing one block (and some small extra data) once per 10 minutes is not going to have any measurable effect on your host's disk throughput. So I wouldn't worry about it at all.

**Comment by polpas** [comment]
I enabled skynet and was worried that my disk access would prevent a good throughput considering placing both consensus and skynet in an ssd volume
