### ISSUE TITLE
Server is unable to create the Sia node

### ISSUE THREAD

**Issue by CryptoPumpkin** [NebulousLabs/docker-sia#63]
Docker host running on Unraid server. The host seems to mess up contract manager file every once in a while. This is a third time it has happened in 1 year of running the host.

## Stack Trace or error message

Sia Daemon v1.5.6
Git Revision 0b253ab18
Loading...
(1/9) Loading siad...
(2/9) Loading gateway...
(3/9) Loading consensus...
(4/9) Loading transaction pool...
(5/9) Loading wallet...
(6/9) Loading feemanager...
(7/9) Loading host...
ERROR: [server is unable to create the Sia node; unable to create host; [error during contract manager startup; error while loading contract manager atomic data; error loading the contract manager settings file; unable to read persisted json object from disk: unexpected end of JSON input]; [error while loading contract manager atomic data; error loading the contract manager settings file; unable to read persisted json object from disk: unexpected end of JSON input]]

[server is unable to create the Sia node; unable to create host; [error during contract manager startup; error while loading contract manager atomic data; error loading the contract manager settings file; unable to read persisted json object from disk: unexpected end of JSON input]; [error while loading contract manager atomic data; error loading the contract manager settings file; unable to read persisted json object from disk: unexpected end of JSON input]]

## Expected Behavior

Load up and run as normal

## Observed Behavior

Error during host loading.

## How to reproduce it (as minimally and precisely as possible)

Random occurence. No idea what is causing it. No idea what would be the proper fix without deleting the contract manager file.

## Environment

Docker running on Unraid

* Sia version:

v1.5.6

* OS:

Unraid (Linux)

**Comment by AndreyNag** [comment]
I have same error Sia version v1.5.9:
`(6/8) Loading host...
(7/8) Loading renter...
ERROR: [server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
[server is unable to create the Sia node; unable to create renter; unable to read persisted json object from disk: loading a file with a bad checksum]
`

**Comment by ro-tex** [comment]
Hello @AndreyNag! 

This seems to be an issue related to the Sia node itself. The best course of action would be to ask on the [Sia Foundation's discord](https://discord.gg/sia) or open an issue at https://github.com/siafoundation/siad. As mentioned in the README, this image has been replaced by ghcr.io/siafoundation/siad and is no longer maintained.
