### ISSUE TITLE
Utilise the upcoming SIAD_DATA_DIR env var

### ISSUE THREAD

**Issue by ro-tex** [NebulousLabs/docker-sia#9]

**Comment by jkawamoto** [comment]
I'm curious what is the difference between `SIA_DATA_DIR` and `SIAD_DATA_DIR`?

**Comment by ro-tex** [comment]
> I'm curious what is the difference between SIA_DATA_DIR and SIAD_DATA_DIR?

From the changelog:  

> Add SIAD_DATA_DIR environment variable which tells `siad` where to store the
>   siad-specific data. This complements the SIA_DATA_DIR variable which tells
>   `siad` where to store general Sia data, such as the API password,
>   configuration, etc.

Under SIAD_DATA_DIR you will find all the important directories such as `consensus`, `wallet`, `host`, `renter`, etc.  
Under SIA_DATA_DIR you will find `apipassword`, Sia-UI's `config.json`, etc.

**Comment by jkawamoto** [comment]
Thanks! So, roughly speaking, current `SIA_DATA_DIR` will be replaced with `SIAD_DATA_DIR` and `SIA_DATA_DIR` will be used for clients.

**Comment by ro-tex** [comment]
`SIAD_DATA_DIR` does not replace `SIA_DATA_DIR` but complements it. If you don't specify one of them both types of data will be stored at the same place. But if you want to store your sensitive `apipassword` and configs at a different location you can now do that.
